#!/bin/sh
set -e

required_version=$(grep app.grails.version application.properties | cut -f 2 -d '=')
local="local-grails-$required_version"

run_local_grails() {
	echo "Using local Grails in $local"
	echo
	GRAILS_HOME="$local" exec "$local/bin/grails" "$@"
}

if [ -d "$local" ]
then
	run_local_grails "$@"
fi

if which -s grails && grails | grep "grails-$required_version" >/dev/null
then
	exec grails "$@"
fi

echo "Can't find Grails $required_version"
zip="grails-$required_version.zip"

if [ ! -f "$zip" ]
then
	url="http://dist.springframework.org.s3.amazonaws.com/release/GRAILS/$zip"
	echo "Downloading from $url"
	curl "$url" --output "$zip"
fi

echo "Unzipping $zip"
unzip "$zip"
unzipped="grails-$required_version"
if [ ! -d "$unzipped" ]
then
	echo "ERROR: expected to find a directory named $unzipped after unzipping $zip"
	exit 1
fi
echo "Moving unzipped files in $unzipped to $local"
mv "$unzipped" "$local"

run_local_grails "$@"

